#!/usr/bin/env bash
# This script provides the custom Homebrew command `brew count`.
# It simply counts the number of installed formulae/casks.

count=$(brew list | wc -l)
echo "You have $count packages installed."
