#! /bin/bash
# alias: brew sync
#:  * `sync` [args...]
#:    `brew sync` is an alias for `brew update --auto-update && brew upgrade -y && ~/bin/mac/bcupg.sh && brew cleanup -s --prune=1`
brew update --auto-update && brew upgrade -y && ~/bin/mac/bcupg.sh && brew cleanup -s --prune=1 "$@"
