name: Bump Formula

on:
  schedule:
    # Time is UTC, so below is running everyday at 4AM and 4PM PST
    - cron: "0 4,16 * * *"
  # Run when this workflow file is changed
  push:
    paths:
      - ".github/workflows/bump-formula.yml"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  bump-formula:
    name: Bump Homebrew Formula
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@1446dca236b0440c6f02723a3f14f13be2c04ab0 #v7
        with:
          # Authentication token to use for pushing changes; use the built-in
          # GITHUB_TOKEN or define a HOMEBREW_TOKEN secret
          token: ${{ secrets.HOMEBREW_TOKEN }}
          # Bump all outdated casks in this tap
          tap: laniksj/homebrew-tap
          # Bump only these formulae if outdated
          formula: fop-rs, lsusb-plus
          livecheck: true
