name: Bump Formula

on:
  # Schedule to run at 4AM and 4PM PST everyday
  schedule:
    - cron: "0 4,16 * * *"
  push:
    paths:
      - ".github/workflows/bump-formula.yml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  bump-formula:
    name: Bump Homebrew Formula
    runs-on: ubuntu-latest
    steps:
      - uses: LanikSJ/homebrew-bump-formula@dc9f66f838da0e4f7b795789a6887a6fbf2267d4 # v1.0.4
        with:
          # Authentication token to use for pushing changes; use the built-in
          # GITHUB_TOKEN or define a HOMEBREW_TOKEN secret
          token: ${{ secrets.HOMEBREW_TOKEN }}
          # Bump all outdated casks in this tap
          tap: laniksj/homebrew-tap
          # Bump only these formulae if outdated
          formula: fop-rs, lsusb-plus
          livecheck: true
