name: Bump Formula

on:
  # Schedule to run at 4AM and 4PM PST everyday
  schedule:
    - cron: "0 4,16 * * *"
  push:
    paths:
      - ".github/workflows/bump-formula.yml"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-formula:
    name: Bump Homebrew Formula
    runs-on: ubuntu-latest
    steps:
      - name: Homebrew Bump Formula (LanikSJ)
        uses: LanikSJ/homebrew-bump-formula@8e23daeb1fd917c509e4c21325a5fe62f1bf5221 # v1.0.5
        with:
          # Authentication token to use for pushing changes; use the built-in
          # GITHUB_TOKEN or define a HOMEBREW_TOKEN secret
          token: ${{ secrets.GITHUB_TOKEN }}
          user_name: ${{ github.actor }}
          user_email: ${{ github.actor }}@users.noreply.github.com
          # Bump all outdated casks in this tap
          tap: laniksj/homebrew-tap
          # Bump only these formulae if outdated
          formula: fop-rs, lsusb-plus
          livecheck: true
